### ISSUE TITLE
openconnect process consumes 100% of a single core forever after rekeying

### ISSUE THREAD

**Issue by senecaso-sf** [dlenski/openconnect#76]
this is a continuation of https://github.com/dlenski/openconnect/issues/73  

All configurations and versions are the same as defined in issue #73 

After switching to the code using the fix provided for #73 , I noticed that after several hours (presumably when a rekey takes place), the one of my CPUs is 100% pinned by the openconnect process.  This doesnt seem to be impacting the VPN at all, as I am still able to connect to sites behind the VPN, however, it is consuming a lot of CPU I would like to reclaim.  I'm guessing something about the rekey process is causing an infinite loop

I tried taking a stack trace to see where the loop is occurring, but I have no symbols apparently, so its not very useful

```
119559: /data/repos/external/openconnect/.libs/lt-openconnect --protocol=gp vpn.example.com --user=my.user --background -...
(No symbols found in )
(No symbols found in /usr/lib/x86_64-linux-gnu/libgnutls.so.30)
(No symbols found in /usr/lib/x86_64-linux-gnu/libxml2.so.2)
(No symbols found in /usr/lib/x86_64-linux-gnu/libproxy.so.1)
(No symbols found in /lib/x86_64-linux-gnu/libc.so.6)
(No symbols found in /lib/x86_64-linux-gnu/libz.so.1)
(No symbols found in /usr/lib/x86_64-linux-gnu/libp11-kit.so.0)
(No symbols found in /usr/lib/x86_64-linux-gnu/libidn.so.11)
(No symbols found in /usr/lib/x86_64-linux-gnu/libtasn1.so.6)
(No symbols found in /usr/lib/x86_64-linux-gnu/libnettle.so.6)
(No symbols found in /usr/lib/x86_64-linux-gnu/libhogweed.so.4)
(No symbols found in /usr/lib/x86_64-linux-gnu/libgmp.so.10)
(No symbols found in /lib/x86_64-linux-gnu/libdl.so.2)
(No symbols found in /usr/lib/x86_64-linux-gnu/libicuuc.so.55)
(No symbols found in /lib/x86_64-linux-gnu/liblzma.so.5)
(No symbols found in /lib/x86_64-linux-gnu/libm.so.6)
(No symbols found in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
(No symbols found in /lib/x86_64-linux-gnu/libgcc_s.so.1)
(No symbols found in /lib64/ld-linux-x86-64.so.2)
(No symbols found in /usr/lib/x86_64-linux-gnu/libffi.so.6)
(No symbols found in /usr/lib/x86_64-linux-gnu/libicudata.so.55)
(No symbols found in /lib/x86_64-linux-gnu/libnss_files.so.2)
(No symbols found in /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2)
(No symbols found in /lib/x86_64-linux-gnu/libnss_dns.so.2)
(No symbols found in /lib/x86_64-linux-gnu/libresolv.so.2)
0x7f0ed9ce021d: _fini + 0x7f0ed98d8ae9 (185197800000000, c6cec90000000000, 1453ce067d5018b, c6cec90000000000, 1767d5018b, 145294000000000) + 313bf5b0a509e134
crawl: Input/output error
Error tracing through process 119559
```

If you can tell me how to build with symbols, I can probably get you a more useful stack trace (sorry, my C/C++ days were years ago)

**Comment by dlenski** [comment]
Thanks for letting me know! I think I've run into this condition myself, but find it hard to reproduce. OpenConnect isn't intended to be a space heater/battery tester. 

What version are you running? The latest af838db4ad?

I believe it is likely caused by the tricky "tap-dance" needed to prevent the `gpst_mainloop` main loop (HTTPS tunnel) and `esp_mainloop` from running simultaneously, and that something is getting screwed up in the connection state model upon reconnect or rekey.

**Comment by dlenski** [comment]
> If you can tell me how to build with symbols, I can probably get you a more useful stack trace (sorry, my C/C++ days were years ago)

Following the guide [here](https://stackoverflow.com/questions/4553735/gnu-autotools-debug-release-targets), this should do it to build with debugging symbols… 

1. Edit `Makefile.am` and add these flags: `AM_CFLAGS = -g3 -O0`
2. `make clean` and then `./autogen.sh` to recreate `Makefile.in` (and `configure`)
3. Run `./configure`, and rebuild as normal

**Comment by senecaso-sf** [comment]
I'm using 7274c12dcf3

I'll try to rebuild and enable debug symbols and get you a stack trace

**Comment by dlenski** [comment]
> I'm using 7274c12

I don't *think* any of the subsequent small bugfixes and cleanup should affect this… but probably best to rebuild from the latest source anyway.

**Comment by senecaso-sf** [comment]
Since moving to the latest build, each time a rekeying takes place, the openconnect process dies and I have to manually restart it.  I'm not sure why... there is nothing in the logs, its just not there anymore.  When I was using 7274c12 the situation was slightly better in that the tunnel would stay up, but it would consume a core.

**Comment by dlenski** [comment]
I found that (very dumb) cookie-handling bug and cleaned up the cookie-handling code to work around it. Sorry about that.

Unfortunately, I cannot reproduce the CPU-consuming bug. After this fix, I hard-coded a rekey interval of 20 seconds and connected to my VPN and tried to furiously `ping` a specific host… after many rekeys, I still don't encounter the 100% CPU consumption. :(

```diff
diff --git a/esp.c b/esp.c
index 7876fd5..80fc982 100644
--- a/esp.c
+++ b/esp.c
@@ -428,7 +429,7 @@ static int gpst_parse_config_xml(struct openconnect_info *vpninfo, xmlNode *xml_
                        int sec = atoi(s);
                        vpn_progress(vpninfo, PRG_INFO, _("Tunnel timeout (rekey interval) is %d minutes.\n"), sec/60);
                        vpninfo->ssl_times.last_rekey = time(NULL);
-                       vpninfo->ssl_times.rekey = sec - 60;
+                       vpninfo->ssl_times.rekey = 20 /*sec - 60*/;
                        vpninfo->ssl_times.rekey_method = REKEY_TUNNEL;
                        free((void *)s);
                } else if (!xmlnode_get_text(xml_node, "gw-address", &s)) {
```

**Comment by senecaso-sf** [comment]
I'll try to revert to 7274c12 and then rebuild with debug symbols and see if that helps reproduce the issue

**Comment by dlenski** [comment]
I did find and find a couple other small issues that affect the rekey process for ESP (a6d34ec, 270651d) so it is probably worth trying the *latest* version to see if it still has the problem.

I couldn't reproduce it with either, though… but there might be something about the timing that I don't understand fully.

**Comment by senecaso-sf** [comment]
Ya, I was using latest, and the CPU issue no longer happens.  Instead the process crashes/exits, which is actually a slightly worse situation for me.  By going back to the older version, I'm hoping I can at least identify where the loop is happening and maybe that will shed some light on why the process is exiting now.

**Comment by dlenski** [comment]
> Ya, I was using latest…

Are you _sure_? I'm all-but-certain that I fixed the crash in 78fc32e.

**Comment by senecaso-sf** [comment]
I didnt check the commit, but `git pull` said I was up to date, and I'm pretty sure I was on master.  Once I reproduce the loop I'll rebuild from master and check if its still crashing again.

**Comment by senecaso-sf** [comment]
Ok, so I was able to reproduce the infinite loop, but I'm still unable to get a `pstack` that has any symbols, despite the binaries all having debug symbols (as reported by `nm -a`).  Not sure how that is happening, but I have now synced back to HEAD, and I have built the latest source (a6d34ec3ec).  I will report back if the process dies or not.

**Comment by dlenski** [comment]
I think I found the bug. That was extremely subtle… argh… hopefully this'll fix your problem.

Commit message for 6b01bc6 has the gory details.

**Comment by senecaso-sf** [comment]
I have been running 6b01bc6 for a day now, and the tunnel is still up and the CPU is not pinned, so it looks like you managed to fix both issues!  Thanks for sorting this out!

**Comment by dlenski** [comment]
> … and the tunnel is still up and the CPU is not pinned, so it looks like you managed to fix both issues!

When you look through the log messages, does the ESP tunnel stop working and switch over to the HTTPS tunnel around the time of the first rekey? Or does it consistently stay in ESP mode?

(The reason I ask is because a failover from ESP → HTTPS is the only way I could manage to trigger the buggy behavior myself.)

**Comment by senecaso-sf** [comment]
Nope.  It used to go from ESP -> HTTPS, but I dont see those messages anymore.  Not sure why that changed.

```
ESP session established with server
ESP tunnel connected; exiting HTTPS mainloop.
GlobalProtect rekey due
```
